services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - postgresql-data:/var/lib/postgresql

volumes:
  postgresql-data:
    driver: local
